//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.02 at 09:24:02 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.varylab.com/2013/09/BlenderMesh", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.varylab.varylab.plugin.blender.data.binding;
